version: '3.8'

services:
  backend:
    build: .
    image: weather:dev
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  chatbot:
    build: .
    image: weather:dev
    command: chatbot
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - backend
